
print(f'{" Bem Vindo ":*^50}')
print('-'*50)
adt = int(input('Informe a quantidade total de PAX: '))
chd = int(input('Informe a quantidade de CHD: '))
inf = int(input('Informe a quantidade de infats: '))
bag = int(input('Informe a quantidade de peças de bagagem: '))
med = float(input('Informe o peso médio das bagagens: '))
cgo = int(input('Informe o peso da carga: '))
cmt = int(input('Informe o peso do comant: '))
dow = int(input('Informe o DOW/PBO da aeronave: '))
acf = str(input('Informe a matricula da Aeronave: ')).strip().upper()
pax = ((adt-chd)*78+(chd*35)+(inf*10))
hold = (bag*med)+cgo+cmt
acft = (acf[:2])+"-"+(acf[2:5])
print('*'*50)
print('-'*50)
print(f'Acft: {acft}, DOW: {dow} Kgs')
print(f'Total de pax: {adt}/{inf}           TTL:{adt-chd}/{chd}/{inf}')
print('-'*50)
print('PESOS:')
print(f'Pax: {pax} Kgs')
print(f'Bagagens {bag} Peças. Total {bag*med:.1f} Kgs')
print(f'Carga: {cgo} Kgs')
print(f'Comat: {cmt} Kgs')
print('-'*50)
print(f'Payload Total: {pax+hold} Kgs')
print(f'-'*50)
print(f'EZFW: {dow+pax+hold}')
print(f'-'*50)
print(f'{" Fim de Programa ":*^50}')



